#!/bin/bash
# ============================================================
# Batch RDS MySQL Upgrade Orchestrator
# ============================================================
#
#  Copyright 2024 Amazon.com, Inc. or its affiliates.
#  Licensed under the Apache License, Version 2.0
#
# Usage:
#   ./batch_upgrade.sh --config <config.yaml> [--dry-run] [--resume]
#                      [--concurrency <N>] [--region <region>]
# ============================================================

set -uo pipefail

CONFIG_PATH=""
DRY_RUN=false
RESUME=false
VALIDATE_CONFIG_ONLY=false
CONCURRENCY=""
REGION=""
SCRIPT_DIR="$(cd "$(dirname "$0")/.." && pwd)"

RED='\033[0;31m'; GREEN='\033[0;32m'
YELLOW='\033[1;33m'; BLUE='\033[0;34m'; NC='\033[0m'
log_info()  { echo -e "${GREEN}[INFO]${NC}  $(date +%H:%M:%S) $*"; }
log_warn()  { echo -e "${YELLOW}[WARN]${NC}  $(date +%H:%M:%S) $*"; }
log_error() { echo -e "${RED}[ERROR]${NC} $(date +%H:%M:%S) $*"; }
log_step()  { echo -e "${BLUE}[STEP]${NC}  $(date +%H:%M:%S) $*"; }

while [[ $# -gt 0 ]]; do
  case "$1" in
    --config) CONFIG_PATH="$2"; shift 2 ;;
    --dry-run) DRY_RUN=true; shift ;;
    --resume) RESUME=true; shift ;;
    --validate-config) VALIDATE_CONFIG_ONLY=true; shift ;;
    --concurrency) CONCURRENCY="$2"; shift 2 ;;
    --region) REGION="$2"; shift 2 ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

if [[ -z "$CONFIG_PATH" ]]; then
  echo "Usage: $0 --config <config.yaml> [--dry-run] [--resume] [--validate-config] [--concurrency <N>] [--region <region>]"
  exit 1
fi

# --- Check prerequisites ---
for cmd in aws jq; do
  if ! command -v "$cmd" &>/dev/null; then
    log_error "$cmd not found. Please install it."
    exit 1
  fi
done

# --- Parse config (supports YAML and JSON) ---
# JSON config is parsed with jq (reliable). YAML uses a simple line parser
# that handles the flat structure generated by generate_config.sh.
# For complex configs, prefer JSON format.
parse_config_json() {
  local config="$1"
  TARGET_VERSION=$(jq -r '.target_version // "8.4.9"' "$config")
  TARGET_PARAM_FAMILY=$(jq -r '.target_param_family // "mysql8.4"' "$config")
  CONFIG_CONCURRENCY=$(jq -r '.concurrency // empty' "$config")
  PRECHECK_PHASE2=$(jq -r '.precheck_phase2 // "false"' "$config")
  CLEANUP_BLUE=$(jq -r '.cleanup_blue_after_switchover // "true"' "$config")
  VALIDATE_GREEN=$(jq -r '.validate_green // "true"' "$config")
  AUTO_SWITCHOVER=$(jq -r '.auto_switchover // "true"' "$config")

  [[ -n "$CONFIG_CONCURRENCY" && -z "$CONCURRENCY" ]] && CONCURRENCY="$CONFIG_CONCURRENCY"
  CONCURRENCY="${CONCURRENCY:-5}"
  PRECHECK_PHASE2="${PRECHECK_PHASE2:-false}"
  CLEANUP_BLUE="${CLEANUP_BLUE:-true}"
  VALIDATE_GREEN="${VALIDATE_GREEN:-true}"
  AUTO_SWITCHOVER="${AUTO_SWITCHOVER:-true}"

  INSTANCE_IDS=()
  INSTANCE_SECRETS=()
  INSTANCE_PARAM_GROUPS=()
  INSTANCE_STRATEGIES=()

  local count
  count=$(jq '.instances | length' "$config")
  for ((i=0; i<count; i++)); do
    INSTANCE_IDS+=("$(jq -r ".instances[$i].instance_id" "$config")")
    INSTANCE_SECRETS+=("$(jq -r ".instances[$i].secret_id // empty" "$config")")
    INSTANCE_PARAM_GROUPS+=("$(jq -r ".instances[$i].source_param_group // empty" "$config")")
    INSTANCE_STRATEGIES+=("$(jq -r ".instances[$i].strategy // \"blue_green\"" "$config")")
  done
}

parse_config_yaml() {
  local config="$1"
  # Extract top-level values
  TARGET_VERSION=$(grep '^target_version:' "$config" | awk '{print $2}' | tr -d '"'"'" | sed 's/#.*//')
  TARGET_PARAM_FAMILY=$(grep '^target_param_family:' "$config" | awk '{print $2}' | tr -d '"'"'" | sed 's/#.*//')
  CONFIG_CONCURRENCY=$(grep '^concurrency:' "$config" | awk '{print $2}' | sed 's/#.*//')
  PRECHECK_PHASE2=$(grep '^precheck_phase2:' "$config" | awk '{print $2}' | sed 's/#.*//')
  CLEANUP_BLUE=$(grep '^cleanup_blue_after_switchover:' "$config" | awk '{print $2}' | sed 's/#.*//')
  VALIDATE_GREEN=$(grep '^validate_green:' "$config" | awk '{print $2}' | sed 's/#.*//')
  AUTO_SWITCHOVER=$(grep '^auto_switchover:' "$config" | awk '{print $2}' | sed 's/#.*//')

  [[ -n "$CONFIG_CONCURRENCY" && -z "$CONCURRENCY" ]] && CONCURRENCY="$CONFIG_CONCURRENCY"
  CONCURRENCY="${CONCURRENCY:-5}"
  PRECHECK_PHASE2="${PRECHECK_PHASE2:-false}"
  CLEANUP_BLUE="${CLEANUP_BLUE:-true}"
  VALIDATE_GREEN="${VALIDATE_GREEN:-true}"
  AUTO_SWITCHOVER="${AUTO_SWITCHOVER:-true}"

  # Extract instances (simple line-by-line parsing)
  INSTANCE_IDS=()
  INSTANCE_SECRETS=()
  INSTANCE_PARAM_GROUPS=()
  INSTANCE_STRATEGIES=()

  local in_instances=false current_id="" current_secret="" current_pg="" current_strategy="blue_green"
  while IFS= read -r line; do
    # Strip inline comments
    line=$(echo "$line" | sed 's/#.*//')
    if [[ "$line" =~ ^instances: ]]; then in_instances=true; continue; fi
    if [[ "$in_instances" == false ]]; then continue; fi
    if [[ "$line" =~ ^[a-z] && ! "$line" =~ ^[[:space:]] ]]; then break; fi

    if [[ "$line" =~ "- instance_id:" ]]; then
      if [[ -n "$current_id" ]]; then
        INSTANCE_IDS+=("$current_id")
        INSTANCE_SECRETS+=("$current_secret")
        INSTANCE_PARAM_GROUPS+=("$current_pg")
        INSTANCE_STRATEGIES+=("$current_strategy")
      fi
      current_id=$(echo "$line" | sed 's/.*instance_id:[[:space:]]*//' | sed 's/#.*//' | tr -d '"'"'" | sed 's/[[:space:]]*$//')
      current_secret="" current_pg="" current_strategy="blue_green"
    elif [[ "$line" =~ "secret_id:" ]]; then
      current_secret=$(echo "$line" | sed 's/.*secret_id:[[:space:]]*//' | sed 's/#.*//' | tr -d '"'"'" | sed 's/[[:space:]]*$//')
    elif [[ "$line" =~ "source_param_group:" ]]; then
      current_pg=$(echo "$line" | sed 's/.*source_param_group:[[:space:]]*//' | sed 's/#.*//' | tr -d '"'"'" | sed 's/[[:space:]]*$//')
    elif [[ "$line" =~ "strategy:" ]]; then
      current_strategy=$(echo "$line" | sed 's/.*strategy:[[:space:]]*//' | sed 's/#.*//' | tr -d '"'"'" | sed 's/[[:space:]]*$//')
    fi
  done < "$config"

  # Last instance
  if [[ -n "$current_id" ]]; then
    INSTANCE_IDS+=("$current_id")
    INSTANCE_SECRETS+=("$current_secret")
    INSTANCE_PARAM_GROUPS+=("$current_pg")
    INSTANCE_STRATEGIES+=("$current_strategy")
  fi
}

parse_config() {
  local config="$1"
  if [[ "$config" == *.json ]]; then
    parse_config_json "$config"
  elif jq . "$config" > /dev/null 2>&1; then
    # File is valid JSON even without .json extension
    parse_config_json "$config"
  else
    parse_config_yaml "$config"
  fi
}

parse_config "$CONFIG_PATH"
TOTAL=${#INSTANCE_IDS[@]}

if [[ "$TOTAL" -eq 0 ]]; then
  log_error "No instances found in config"; exit 1
fi

# --- Validate config mode (no AWS calls) ---
if [[ "$VALIDATE_CONFIG_ONLY" == "true" ]]; then
  echo "============================================================"
  echo "Config Validation: $CONFIG_PATH"
  echo "============================================================"
  echo "Target version:    $TARGET_VERSION"
  echo "Param family:      $TARGET_PARAM_FAMILY"
  echo "Concurrency:       $CONCURRENCY"
  echo "Precheck phase2:   $PRECHECK_PHASE2"
  echo "Cleanup blue:      $CLEANUP_BLUE"
  echo "Validate green:    $VALIDATE_GREEN"
  echo "Auto switchover:   $AUTO_SWITCHOVER"
  echo "Total instances:   $TOTAL"
  echo "------------------------------------------------------------"

  ERRORS=0
  BG_COUNT=0
  IP_COUNT=0

  for ((i=0; i<TOTAL; i++)); do
    id="${INSTANCE_IDS[$i]}"
    secret="${INSTANCE_SECRETS[$i]}"
    pg="${INSTANCE_PARAM_GROUPS[$i]}"
    strategy="${INSTANCE_STRATEGIES[$i]}"

    # Validate strategy
    if [[ "$strategy" != "blue_green" && "$strategy" != "in_place" ]]; then
      echo "  ERROR: [$id] Invalid strategy: '$strategy' (must be blue_green or in_place)"
      ERRORS=$((ERRORS + 1))
    elif [[ "$strategy" == "blue_green" ]]; then
      BG_COUNT=$((BG_COUNT + 1))
    else
      IP_COUNT=$((IP_COUNT + 1))
    fi

    # Validate instance_id not empty
    if [[ -z "$id" ]]; then
      echo "  ERROR: Instance #$((i+1)) has empty instance_id"
      ERRORS=$((ERRORS + 1))
      continue
    fi

    # Report
    printf "  %-30s strategy=%-10s secret=%-5s param_group=%s\n" \
      "$id" "$strategy" "${secret:+yes}" "${pg:-auto-detect}"
  done

  echo "------------------------------------------------------------"
  echo "Blue/Green:  $BG_COUNT"
  echo "In-place:    $IP_COUNT"
  echo "------------------------------------------------------------"

  if [[ "$ERRORS" -gt 0 ]]; then
    echo "VALIDATION FAILED: $ERRORS error(s) found."
    exit 1
  else
    echo "VALIDATION PASSED: Config is valid."
    exit 0
  fi
fi

REGION_ARGS=()
[[ -n "$REGION" ]] && REGION_ARGS=(--region "$REGION")

# --- State file ---
STATE_DIR="$(dirname "$CONFIG_PATH")"
STATE_FILE="${STATE_DIR}/batch_state_$(date +%Y%m%d_%H%M%S).json"
REPORT_DIR="${STATE_DIR}/logs"
mkdir -p "$REPORT_DIR"

if [[ "$RESUME" == "true" ]]; then
  LATEST_STATE=$(ls -t "${STATE_DIR}"/batch_state_*.json 2>/dev/null | head -1)
  if [[ -n "$LATEST_STATE" ]]; then
    STATE_FILE="$LATEST_STATE"
    log_info "Resuming from: $STATE_FILE"
  fi
fi

init_state() {
  local instances_json='{'
  for ((i=0; i<TOTAL; i++)); do
    [[ $i -gt 0 ]] && instances_json+=','
    instances_json+='"'"${INSTANCE_IDS[$i]}"'":{"status":"PENDING"}'
  done
  instances_json+='}'
  jq -n --arg id "upgrade_$(date +%Y%m%d_%H%M%S)" --argjson inst "$instances_json" \
    '{batch_id: $id, started_at: (now | strftime("%Y-%m-%dT%H:%M:%SZ")), instances: $inst}' > "$STATE_FILE"
}

get_status() {
  (
    flock -s 200
    jq -r --arg id "$1" '.instances[$id].status' "$STATE_FILE"
  ) 200>"${STATE_FILE}.lock"
}

set_status() {
  local id="$1" status="$2" extra="${3:-}"
  (
    flock -x 200
    local tmp=$(mktemp)
    if [[ -n "$extra" ]]; then
      jq --arg id "$id" --arg s "$status" --arg e "$extra" \
        '.instances[$id].status = $s | .instances[$id].detail = $e' "$STATE_FILE" > "$tmp"
    else
      jq --arg id "$id" --arg s "$status" '.instances[$id].status = $s' "$STATE_FILE" > "$tmp"
    fi
    mv "$tmp" "$STATE_FILE"
  ) 200>"${STATE_FILE}.lock"
}

if [[ "$RESUME" != "true" || ! -f "$STATE_FILE" ]]; then
  init_state
fi

# --- Parameter group dedup ---
# Note: Using temp file instead of associative array for bash 3.x compatibility
PARAM_GROUP_MAP_FILE=$(mktemp /tmp/pg_map_XXXXXX)
MIGRATED_GROUPS=()

# --- Cluster dedup (skip duplicate cluster members) ---
UPGRADED_CLUSTERS_FILE=$(mktemp /tmp/cluster_done_XXXXXX)

migrate_param_group_once() {
  local source_pg="$1"
  if [[ -z "$source_pg" ]]; then return; fi
  if grep -q "^${source_pg}=" "$PARAM_GROUP_MAP_FILE" 2>/dev/null; then
    log_info "Parameter group '$source_pg' already migrated to '$(grep "^${source_pg}=" "$PARAM_GROUP_MAP_FILE" | cut -d= -f2)'"
    return
  fi

  local target_pg="${source_pg}-${TARGET_PARAM_FAMILY//./}"
  log_step "Migrating parameter group: $source_pg → $target_pg (family: $TARGET_PARAM_FAMILY)"

  if [[ "$DRY_RUN" == "true" ]]; then
    log_warn "[DRY RUN] Would migrate $source_pg → $target_pg"
    echo "${source_pg}=${target_pg}" >> "$PARAM_GROUP_MAP_FILE"
    return
  fi

  local migrate_script="$SCRIPT_DIR/params/migrate_param_group.sh"
  if [[ -f "$migrate_script" ]]; then
    "$migrate_script" -s "$source_pg" -t "$target_pg" -f "$TARGET_PARAM_FAMILY" ${REGION_ARGS[@]+"${REGION_ARGS[@]}"} || {
      log_warn "Parameter migration failed for $source_pg. Target group may already exist."
    }
  else
    log_warn "migrate_param_group.sh not found. Skipping parameter migration."
  fi
  echo "${source_pg}=${target_pg}" >> "$PARAM_GROUP_MAP_FILE"
}

# --- Option group dedup ---
OPTION_GROUP_MAP_FILE=$(mktemp /tmp/og_map_XXXXXX)

migrate_option_group_once() {
  local instance_id="$1"
  if [[ -z "$instance_id" ]]; then return; fi

  # Get current option group
  local source_og
  source_og=$(aws rds describe-db-instances ${REGION_ARGS[@]+"${REGION_ARGS[@]}"} \
    --db-instance-identifier "$instance_id" \
    --query 'DBInstances[0].OptionGroupMemberships[0].OptionGroupName' \
    --output text 2>/dev/null || echo "")

  # Skip default option groups
  if [[ -z "$source_og" || "$source_og" == default:* || "$source_og" == "None" ]]; then
    return
  fi

  # Already migrated this option group
  if grep -q "^${source_og}=" "$OPTION_GROUP_MAP_FILE" 2>/dev/null; then
    log_info "Option group '$source_og' already migrated to '$(grep "^${source_og}=" "$OPTION_GROUP_MAP_FILE" | cut -d= -f2)'"
    return
  fi

  log_step "Migrating option group: $source_og"

  local check_script="$SCRIPT_DIR/params/check_option_group.sh"
  if [[ ! -f "$check_script" ]]; then
    log_warn "check_option_group.sh not found. Skipping option group migration."
    return
  fi

  local og_args=(--instance-id "$instance_id")
  [[ -n "${REGION:-}" ]] && og_args+=(--region "$REGION")

  if [[ "$DRY_RUN" == "true" ]]; then
    og_args+=(--dry-run)
  fi

  local og_result
  og_result=$("$check_script" "${og_args[@]}" --json 2>/dev/null) || true
  local target_og
  target_og=$(echo "$og_result" | jq -r '.target_option_group // empty' 2>/dev/null)

  if [[ -n "$target_og" ]]; then
    echo "${source_og}=${target_og}" >> "$OPTION_GROUP_MAP_FILE"
    log_info "Option group '$source_og' → '$target_og'"
  fi
}

# --- Upgrade single instance ---
upgrade_instance() {
  local idx="$1"
  local id="${INSTANCE_IDS[$idx]}"
  local secret="${INSTANCE_SECRETS[$idx]}"
  local source_pg="${INSTANCE_PARAM_GROUPS[$idx]}"
  local strategy="${INSTANCE_STRATEGIES[$idx]}"

  # Auto-detect Green instance (B/G two-step) — force in_place
  # This is a safety net; generate_config.sh already assigns in_place for green instances.
  # Uses naming convention as heuristic — authoritative check is in discover_instances.sh
  # which uses actual B/G deployment data (blue_green_role field).
  if [[ "$id" == *-green-* && "$strategy" == "blue_green" ]]; then
    log_warn "$id: Appears to be a Green instance (B/G two-step). Forcing in_place."
    strategy="in_place"
  fi

  # Auto-detect Multi-AZ DB Cluster — force in_place (Blue/Green not supported)
  local cluster_id
  cluster_id=$(aws rds describe-db-instances ${REGION_ARGS[@]+"${REGION_ARGS[@]}"} \
    --db-instance-identifier "$id" \
    --query 'DBInstances[0].DBClusterIdentifier' --output text 2>/dev/null || echo "")

  if [[ -n "$cluster_id" && "$cluster_id" != "None" ]]; then
    # Skip if this cluster was already upgraded via another member
    if grep -q "^${cluster_id}$" "$UPGRADED_CLUSTERS_FILE" 2>/dev/null; then
      log_info "$id: Cluster '$cluster_id' already upgraded via another member. Skipping."
      set_status "$id" "COMPLETED" "Cluster upgraded via primary"
      return
    fi

    if [[ "$strategy" == "blue_green" ]]; then
      log_warn "$id: Member of Multi-AZ DB Cluster '$cluster_id' — Blue/Green not supported. Forcing in_place."
      strategy="in_place"
    fi

    # Show which instances belong to this cluster
    local cluster_members
    cluster_members=$(aws rds describe-db-clusters ${REGION_ARGS[@]+"${REGION_ARGS[@]}"} \
      --db-cluster-identifier "$cluster_id" \
      --query 'DBClusters[0].DBClusterMembers[].DBInstanceIdentifier' \
      --output text 2>/dev/null || echo "$id")
    log_info "$id: Will upgrade cluster '$cluster_id' (members: $cluster_members)"
    echo "$cluster_id" >> "$UPGRADED_CLUSTERS_FILE"
  fi

  # Determine the upgrade target: cluster ID for clusters, instance ID otherwise
  local upgrade_target="$id"
  if [[ -n "$cluster_id" && "$cluster_id" != "None" ]]; then
    upgrade_target="$cluster_id"
  fi

  log_info "========== [$((idx+1))/$TOTAL] $upgrade_target (strategy: $strategy) =========="

  # Auto-detect source param group if not specified (always use instance ID)
  if [[ -z "$source_pg" ]]; then
    source_pg=$(aws rds describe-db-instances ${REGION_ARGS[@]+"${REGION_ARGS[@]}"} \
      --db-instance-identifier "$id" \
      --query 'DBInstances[0].DBParameterGroups[0].DBParameterGroupName' --output text 2>/dev/null || echo "")
  fi

  # Step 1: Precheck (use instance ID for endpoint lookup)
  log_step "Step 1: Running precheck on $id"
  if [[ "$DRY_RUN" == "true" ]]; then
    log_warn "[DRY RUN] Would run precheck on $id"
  else
    local host
    host=$(aws rds describe-db-instances ${REGION_ARGS[@]+"${REGION_ARGS[@]}"} \
      --db-instance-identifier "$id" \
      --query 'DBInstances[0].Endpoint.Address' --output text 2>/dev/null || echo "")

    if [[ -n "$host" && -n "$secret" ]]; then
      local precheck_args=(-h "$host" --secret-id "$secret" --json)
      [[ "$PRECHECK_PHASE2" == "true" ]] && precheck_args+=(--phase2)

      local precheck_user
      precheck_user=$(aws secretsmanager get-secret-value --secret-id "$secret" \
        --query SecretString --output text 2>/dev/null | jq -r '.username // "admin"')

      precheck_args+=(-u "$precheck_user")

      PRECHECK_RESULT=$("$SCRIPT_DIR/precheck/mysql_precheck_run.sh" "${precheck_args[@]}" 2>/dev/null || echo '{"summary":{"errors":999}}')
      PRECHECK_ERRORS=$(echo "$PRECHECK_RESULT" | jq -r '.summary.errors // 999')

      if [[ "$PRECHECK_ERRORS" -gt 0 ]]; then
        log_error "$id: Precheck found $PRECHECK_ERRORS error(s). Skipping."
        set_status "$id" "SKIPPED" "Precheck: $PRECHECK_ERRORS error(s)"
        return
      fi
      log_info "$id: Precheck passed"
    else
      log_warn "$id: Cannot run precheck (no endpoint or secret). Continuing..."
    fi
  fi

  # Step 2: Migrate parameter group (dedup)
  if [[ -n "$source_pg" && "$source_pg" != "default."* ]]; then
    migrate_param_group_once "$source_pg"
  fi
  local target_pg="$(grep "^${source_pg}=" "$PARAM_GROUP_MAP_FILE" 2>/dev/null | cut -d= -f2)"

  # Step 2b: Migrate option group (dedup)
  migrate_option_group_once "$id"
  local source_og
  source_og=$(aws rds describe-db-instances ${REGION_ARGS[@]+"${REGION_ARGS[@]}"} \
    --db-instance-identifier "$id" \
    --query 'DBInstances[0].OptionGroupMemberships[0].OptionGroupName' \
    --output text 2>/dev/null || echo "")
  local target_og=""
  if [[ -n "$source_og" && "$source_og" != default:* && "$source_og" != "None" ]]; then
    target_og="$(grep "^${source_og}=" "$OPTION_GROUP_MAP_FILE" 2>/dev/null | cut -d= -f2)"
  fi

  set_status "$id" "IN_PROGRESS"

  # Step 3: Execute upgrade based on strategy
  if [[ "$strategy" == "blue_green" ]]; then
    upgrade_blue_green "$id" "$target_pg" "$target_og"
  elif [[ "$strategy" == "in_place" ]]; then
    # For clusters, pass cluster ID but track status with instance ID
    if [[ "$upgrade_target" != "$id" ]]; then
      # Cluster upgrade — call in_place_upgrade.sh directly (skip set_status inside)
      log_step "Step 3: In-place upgrade for cluster '$upgrade_target' → MySQL $TARGET_VERSION"
      local up_args=(--instance-id "$upgrade_target" --target-version "$TARGET_VERSION" --apply-immediately)
      [[ -n "$target_pg" ]] && up_args+=(--target-param-group "$target_pg")
      [[ -n "$target_og" ]] && up_args+=(--target-option-group "$target_og")
      [[ -n "$REGION" ]] && up_args+=(--region "$REGION")

      if [[ "$DRY_RUN" == "true" ]]; then
        log_warn "[DRY RUN] Would in-place upgrade cluster $upgrade_target"
        set_status "$id" "COMPLETED" "DRY RUN"
      else
        "$SCRIPT_DIR/upgrade/in_place_upgrade.sh" "${up_args[@]}" || {
          log_error "$id: In-place cluster upgrade failed ($upgrade_target)"
          set_status "$id" "FAILED" "In-place cluster upgrade failed"
          return
        }
        set_status "$id" "COMPLETED" "Cluster $upgrade_target upgraded"
        log_info "$id: Cluster '$upgrade_target' upgrade completed successfully"
      fi
    else
      upgrade_in_place "$id" "$target_pg" "$target_og"
    fi
  else
    log_error "$id: Unknown strategy '$strategy'"
    set_status "$id" "FAILED" "Unknown strategy: $strategy"
    return
  fi
}

upgrade_blue_green() {
  local id="$1" target_pg="$2" target_og="${3:-}"

  if [[ "$DRY_RUN" == "true" ]]; then
    log_warn "[DRY RUN] Would create Blue/Green for $id"
    set_status "$id" "COMPLETED" "DRY RUN"
    return
  fi

  # Check if instance already has an active Blue/Green deployment
  local DEPLOYMENT_ID=""
  local source_arn
  source_arn=$(aws rds describe-db-instances ${REGION_ARGS[@]+"${REGION_ARGS[@]}"} \
    --db-instance-identifier "$id" \
    --query 'DBInstances[0].DBInstanceArn' --output text 2>/dev/null || echo "")

  if [[ -n "$source_arn" && "$source_arn" != "None" ]]; then
    local existing_bg
    existing_bg=$(aws rds describe-blue-green-deployments ${REGION_ARGS[@]+"${REGION_ARGS[@]}"} \
      --query "BlueGreenDeployments[?Source=='${source_arn}' && Status!='DELETED' && Status!='DELETING'] | [0]" \
      --output json 2>/dev/null || echo "null")

    if [[ "$existing_bg" != "null" && "$existing_bg" != "None" && -n "$existing_bg" ]]; then
      DEPLOYMENT_ID=$(echo "$existing_bg" | jq -r '.BlueGreenDeploymentIdentifier // empty')
      local existing_status=$(echo "$existing_bg" | jq -r '.Status // empty')

      if [[ -n "$DEPLOYMENT_ID" ]]; then
        log_warn "$id: Existing Blue/Green deployment found: $DEPLOYMENT_ID (status: $existing_status)"
        case "$existing_status" in
          AVAILABLE)
            log_info "$id: Deployment already AVAILABLE. Skipping creation, proceeding to validate."
            ;;
          PROVISIONING)
            log_info "$id: Deployment still PROVISIONING. Proceeding to monitor."
            ;;
          SWITCHOVER_IN_PROGRESS)
            log_info "$id: Switchover already in progress. Waiting for completion."
            ;;
          *)
            log_error "$id: Existing deployment in unexpected state: $existing_status"
            set_status "$id" "FAILED" "Existing B/G in state: $existing_status"
            return
            ;;
        esac
      fi
    fi
  fi

  # Create new deployment if none exists
  if [[ -z "$DEPLOYMENT_ID" ]]; then
    log_step "Step 3: Creating Blue/Green deployment for instance '$id'"

    # Detect if instance has a custom option group — forces two-step B/G
    # (RDS doesn't allow major version upgrade + custom option group in one call)
    local has_custom_og=false
    local instance_og
    instance_og=$(aws rds describe-db-instances ${REGION_ARGS[@]+"${REGION_ARGS[@]}"} \
      --db-instance-identifier "$id" \
      --query 'DBInstances[0].OptionGroupMemberships[0].OptionGroupName' \
      --output text 2>/dev/null || echo "")
    if [[ -n "$instance_og" && "$instance_og" != default:* && "$instance_og" != "None" ]]; then
      has_custom_og=true
      log_warn "$id: Custom option group '$instance_og' detected. Using two-step B/G (create same-version → upgrade green)."
    fi

    local bg_args=(--instance-id "$id")
    if [[ "$has_custom_og" == "false" ]]; then
      bg_args+=(--target-version "$TARGET_VERSION")
    fi
    [[ -n "$target_pg" && "$has_custom_og" == "false" ]] && bg_args+=(--target-param-group "$target_pg")
    [[ -n "$target_og" ]] && bg_args+=(--target-option-group "$target_og")
    [[ -n "$REGION" ]] && bg_args+=(--region "$REGION")

    BG_RESULT=$("$SCRIPT_DIR/upgrade/create_blue_green.sh" "${bg_args[@]}") || {
      log_error "$id: Blue/Green creation failed"
      log_warn  "$id: Consider using in-place upgrade instead (causes downtime):"
      log_warn  "  ./scripts/upgrade/in_place_upgrade.sh --instance-id $id --target-version $TARGET_VERSION --apply-immediately"
      log_warn  "$id: Common reasons: cascading replicas, CloudFormation-managed, or unsupported configuration."
      log_warn  "$id: See: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/blue-green-deployments.html#blue-green-deployments-limitations"
      set_status "$id" "FAILED" "B/G creation failed — consider in-place upgrade"
      return
    }

    DEPLOYMENT_ID=$(echo "$BG_RESULT" | jq -r '.deployment_id')
    UPGRADE_GREEN=$(echo "$BG_RESULT" | jq -r '.upgrade_green_required // false')
    log_info "$id: Deployment created: $DEPLOYMENT_ID"
    if [[ "$UPGRADE_GREEN" == "true" ]]; then
      log_info "$id: Two-step mode (custom option group). Green will be upgraded as soon as it's available."
    fi
  fi

  # Step 4b: Upgrade green instance early (two-step mode for custom option groups)
  # Green instance becomes available before the full deployment is AVAILABLE.
  # We can start the version upgrade immediately without waiting for deployment completion.
  if [[ "${UPGRADE_GREEN:-false}" == "true" ]]; then
    log_step "Step 4b: Waiting for green instance to become available, then upgrading to $TARGET_VERSION"

    # Get green instance ID from deployment
    local green_instance_id=""
    local wait_start=$(date +%s)
    while [[ -z "$green_instance_id" || "$green_instance_id" == "None" ]]; do
      local green_arn
      green_arn=$(aws rds describe-blue-green-deployments ${REGION_ARGS[@]+"${REGION_ARGS[@]}"} \
        --blue-green-deployment-identifier "$DEPLOYMENT_ID" \
        --query 'BlueGreenDeployments[0].SwitchoverDetails[?TargetMember!=null] | [0].TargetMember' \
        --output text 2>/dev/null || echo "")
      green_instance_id=$(echo "$green_arn" | grep -o '[^:]*$')
      if [[ -z "$green_instance_id" || "$green_instance_id" == "None" ]]; then
        local w_elapsed=$(( $(date +%s) - wait_start ))
        if [[ "$w_elapsed" -ge 600 ]]; then
          log_error "$id: Timeout waiting for green instance to appear (600s)"
          set_status "$id" "FAILED" "Green instance not found"
          return
        fi
        sleep 30
      fi
    done

    # Wait for green instance to be available (may still be restoring)
    log_info "$id: Green instance: $green_instance_id. Waiting for available status..."
    while true; do
      local g_status
      g_status=$(aws rds describe-db-instances ${REGION_ARGS[@]+"${REGION_ARGS[@]}"} \
        --db-instance-identifier "$green_instance_id" \
        --query 'DBInstances[0].DBInstanceStatus' --output text 2>/dev/null || echo "unknown")
      if [[ "$g_status" == "available" ]]; then
        break
      fi
      local w_elapsed=$(( $(date +%s) - wait_start ))
      if [[ "$w_elapsed" -ge 3600 ]]; then
        log_error "$id: Timeout waiting for green instance available (3600s)"
        set_status "$id" "FAILED" "Green instance not available"
        return
      fi
      log_info "  [$green_instance_id] Status: $g_status (${w_elapsed}s)"
      sleep 30
    done

    # Upgrade green instance immediately (don't wait for full deployment AVAILABLE)
    log_info "$id: Green instance available. Starting version upgrade..."
    local modify_args=(--db-instance-identifier "$green_instance_id"
      --engine-version "$TARGET_VERSION" --allow-major-version-upgrade --apply-immediately)
    [[ -n "$target_pg" ]] && modify_args+=(--db-parameter-group-name "$target_pg")
    modify_args+=(${REGION_ARGS[@]+"${REGION_ARGS[@]}"})

    aws rds modify-db-instance "${modify_args[@]}" --output json > /dev/null 2>&1 || {
      log_error "$id: Failed to upgrade green instance '$green_instance_id'"
      set_status "$id" "FAILED" "Green instance upgrade failed"
      return
    }

    # Wait for green instance upgrade to complete
    log_info "$id: Waiting for green instance upgrade..."
    local green_start=$(date +%s)
    while true; do
      local green_status
      green_status=$(aws rds describe-db-instances ${REGION_ARGS[@]+"${REGION_ARGS[@]}"} \
        --db-instance-identifier "$green_instance_id" \
        --query 'DBInstances[0].[DBInstanceStatus,EngineVersion]' --output text 2>/dev/null)
      local g_status=$(echo "$green_status" | awk '{print $1}')
      local g_version=$(echo "$green_status" | awk '{print $2}')
      local g_elapsed=$(( $(date +%s) - green_start ))

      log_info "  [$green_instance_id] Status: $g_status, Version: $g_version (${g_elapsed}s)"

      if [[ "$g_status" == "available" && "$g_version" == "$TARGET_VERSION"* ]]; then
        log_info "$id: Green instance upgraded to $g_version"
        break
      fi
      if [[ "$g_elapsed" -ge 7200 ]]; then
        log_error "$id: Green instance upgrade timeout after 7200s"
        set_status "$id" "FAILED" "Green instance upgrade timeout"
        return
      fi
      sleep 60
    done
  fi

  # Step 4c: Wait for full deployment AVAILABLE (needed for switchover)
  log_step "Step 4c: Waiting for deployment AVAILABLE"
  "$SCRIPT_DIR/upgrade/monitor_blue_green.sh" --deployment-id "$DEPLOYMENT_ID" ${REGION:+--region "$REGION"} || {
    log_error "$id: Blue/Green deployment failed"
    set_status "$id" "FAILED" "B/G deployment failed"
    return
  }

  # Step 5: Validate green environment (optional)
  if [[ "$VALIDATE_GREEN" == "true" ]]; then
    log_step "Step 5: Validating green environment"
    local green_id="${id}-green-*"
    # Get green instance endpoint from deployment
    local green_endpoint
    green_endpoint=$(aws rds describe-blue-green-deployments ${REGION_ARGS[@]+"${REGION_ARGS[@]}"} \
      --blue-green-deployment-identifier "$DEPLOYMENT_ID" \
      --query 'BlueGreenDeployments[0].SwitchoverDetails[?TargetMember!=null] | [0].TargetMember' \
      --output text 2>/dev/null || echo "")

    if [[ -n "$green_endpoint" && "$green_endpoint" != "None" ]]; then
      # Extract green instance ID from ARN
      local green_instance_id
      green_instance_id=$(echo "$green_endpoint" | grep -o '[^:]*$')
      log_info "$id: Green instance: $green_instance_id"

      # Run infra validation on green
      local validate_output
      validate_output=$("$SCRIPT_DIR/validate/post_upgrade_validate.sh" --instance-id "$green_instance_id" \
        ${REGION:+--region "$REGION"} --expected-version "$TARGET_VERSION" --json 2>/dev/null) || true

      # Save validation report
      echo "$validate_output" > "$REPORT_DIR/${id}_validate_green.json" 2>/dev/null
      log_info "$id: Validation report saved to $REPORT_DIR/${id}_validate_green.json"

      # Check for failures
      local validate_status
      validate_status=$(echo "$validate_output" | jq -r '.overall // "UNKNOWN"' 2>/dev/null)
      if [[ "$validate_status" == "FAIL" ]]; then
        log_warn "$id: Green environment validation had issues (non-blocking)"
      fi
    else
      log_warn "$id: Could not determine green instance. Skipping green validation."
    fi
  else
    log_info "$id: Skipping green validation (validate_green=false)"
  fi

  # Step 6: Pre-switchover readiness check
  log_step "Step 6: Pre-switchover readiness check"
  PRE_SW_RESULT=$("$SCRIPT_DIR/upgrade/pre_switchover_check.sh" --deployment-id "$DEPLOYMENT_ID" ${REGION:+--region "$REGION"} --json 2>/dev/null) || true
  PRE_SW_OVERALL=$(echo "$PRE_SW_RESULT" | jq -r '.overall // "UNKNOWN"' 2>/dev/null)

  if [[ "$PRE_SW_OVERALL" != "PASS" ]]; then
    PRE_SW_FAILURES=$(echo "$PRE_SW_RESULT" | jq -r '[.checks[] | select(.status == "FAIL")] | map("\(.name): \(.detail)") | join("; ")' 2>/dev/null)
    log_error "$id: Pre-switchover check failed: $PRE_SW_FAILURES"
    log_warn  "$id: Remediation hints:"
    echo "$PRE_SW_RESULT" | jq -r '.checks[] | select(.status == "FAIL") | .name' 2>/dev/null | while read -r check_name; do
      case "$check_name" in
        deployment_status) log_warn "  - Wait for deployment to reach AVAILABLE status, or check for provisioning errors" ;;
        green_instance_status) log_warn "  - Green instance not available. Check RDS events for errors during upgrade" ;;
        blue_instance_status) log_warn "  - Blue instance not available. Check if maintenance or modification is in progress" ;;
        replication_health) log_warn "  - Replication degraded. Check for DDL/DML conflicts or high write load on blue" ;;
        external_replication) log_warn "  - Blue is an external replica. Stop external replication before switchover" ;;
        *) log_warn "  - Check AWS docs: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/blue-green-deployments-switching.html" ;;
      esac
    done
    set_status "$id" "FAILED" "Pre-switchover: $PRE_SW_FAILURES"
    return
  fi
  log_info "$id: Pre-switchover check passed"

  # Gate: auto_switchover=false stops here (user will resume later)
  if [[ "$AUTO_SWITCHOVER" == "false" ]]; then
    log_info "$id: auto_switchover=false. Stopping before switchover."
    log_info "$id: Green environment is ready. Deployment: $DEPLOYMENT_ID"
    log_info "$id: When ready, resume with: --resume (or manually run switchover)"
    set_status "$id" "PENDING_SWITCHOVER" "Awaiting manual switchover: $DEPLOYMENT_ID"
    return
  fi

  log_step "Step 7: Executing switchover"
  "$SCRIPT_DIR/upgrade/switchover_blue_green.sh" --deployment-id "$DEPLOYMENT_ID" ${REGION:+--region "$REGION"} || {
    log_error "$id: Switchover failed"
    set_status "$id" "FAILED" "Switchover failed"
    return
  }

  # Step 8: Connectivity check
  log_step "Step 8: Post-switchover connectivity check"
  local post_sw_output
  post_sw_output=$("$SCRIPT_DIR/validate/post_upgrade_validate.sh" --instance-id "$id" \
    ${REGION:+--region "$REGION"} --expected-version "$TARGET_VERSION" --json 2>/dev/null) || true
  echo "$post_sw_output" > "$REPORT_DIR/${id}_post_switchover.json" 2>/dev/null

  local post_sw_status
  post_sw_status=$(echo "$post_sw_output" | jq -r '.overall // "UNKNOWN"' 2>/dev/null)
  if [[ "$post_sw_status" == "FAIL" ]]; then
    log_warn "$id: Post-switchover validation had issues"
  fi

  # Step 9: Cleanup
  if [[ "$CLEANUP_BLUE" == "true" ]]; then
    log_step "Step 9: Cleaning up Blue/Green deployment"
    "$SCRIPT_DIR/upgrade/cleanup_blue_green.sh" --deployment-id "$DEPLOYMENT_ID" ${REGION:+--region "$REGION"} --delete-source || {
      log_warn "$id: Cleanup failed (non-critical)"
    }
  fi

  set_status "$id" "COMPLETED"
  log_info "$id: Upgrade completed successfully"
}

upgrade_in_place() {
  local id="$1" target_pg="$2" target_og="${3:-}"

  if [[ "$DRY_RUN" == "true" ]]; then
    log_warn "[DRY RUN] Would in-place upgrade $id"
    set_status "$id" "COMPLETED" "DRY RUN"
    return
  fi

  log_step "Step 3: In-place upgrade for '$id' → MySQL $TARGET_VERSION"
  local up_args=(--instance-id "$id" --target-version "$TARGET_VERSION" --apply-immediately)
  [[ -n "$target_pg" ]] && up_args+=(--target-param-group "$target_pg")
  [[ -n "$target_og" ]] && up_args+=(--target-option-group "$target_og")
  [[ -n "$REGION" ]] && up_args+=(--region "$REGION")

  "$SCRIPT_DIR/upgrade/in_place_upgrade.sh" "${up_args[@]}" || {
    log_error "$id: In-place upgrade failed"
    set_status "$id" "FAILED" "In-place upgrade failed"
    return
  }

  log_step "Step 4: Post-upgrade validation"
  "$SCRIPT_DIR/validate/post_upgrade_validate.sh" --instance-id "$id" ${REGION:+--region "$REGION"} --expected-version "$TARGET_VERSION" || {
    log_warn "$id: Validation had issues"
  }

  set_status "$id" "COMPLETED"
  log_info "$id: Upgrade completed successfully"
}

# --- Main execution ---
log_info "============================================================"
log_info "Batch RDS MySQL Upgrade"
log_info "============================================================"
log_info "Config:       $CONFIG_PATH"
log_info "Target:       MySQL $TARGET_VERSION"
log_info "Instances:    $TOTAL"
log_info "Concurrency:  $CONCURRENCY"
log_info "Dry run:      $DRY_RUN"
log_info "State file:   $STATE_FILE"
log_info "============================================================"

ACTIVE_JOBS=0
PIDS=()
START_TIME=$(date +%s)

for ((i=0; i<TOTAL; i++)); do
  id="${INSTANCE_IDS[$i]}"
  current_status=$(get_status "$id")

  if [[ "$current_status" == "COMPLETED" || "$current_status" == "SKIPPED" ]]; then
    log_info "$id: Already $current_status, skipping"
    continue
  fi

  # Concurrency control (bash 4.2+ compatible — no wait -n)
  while [[ "$ACTIVE_JOBS" -ge "$CONCURRENCY" ]]; do
    # Wait for any one background job to finish
    local_wait_done=false
    for pid_idx in "${!PIDS[@]}"; do
      if ! kill -0 "${PIDS[$pid_idx]}" 2>/dev/null; then
        wait "${PIDS[$pid_idx]}" 2>/dev/null || true
        unset 'PIDS[pid_idx]'
        ACTIVE_JOBS=$((ACTIVE_JOBS - 1))
        local_wait_done=true
        break
      fi
    done
    if [[ "$local_wait_done" == "false" ]]; then
      sleep 5
    fi
  done

  if [[ "$CONCURRENCY" -gt 1 ]]; then
    upgrade_instance "$i" &
    PIDS+=($!)
    ACTIVE_JOBS=$((ACTIVE_JOBS + 1))
  else
    upgrade_instance "$i"
  fi
done

# Wait for remaining jobs
wait

ELAPSED=$(( $(date +%s) - START_TIME ))

# --- Cleanup temp files ---
rm -f "$PARAM_GROUP_MAP_FILE" "$OPTION_GROUP_MAP_FILE" "$UPGRADED_CLUSTERS_FILE" "${STATE_FILE}.lock" 2>/dev/null

# --- Summary ---
COMPLETED=$(jq '[.instances[] | select(.status == "COMPLETED")] | length' "$STATE_FILE")
FAILED=$(jq '[.instances[] | select(.status == "FAILED")] | length' "$STATE_FILE")
SKIPPED=$(jq '[.instances[] | select(.status == "SKIPPED")] | length' "$STATE_FILE")

log_info "============================================================"
log_info "Batch Upgrade Summary"
log_info "============================================================"
log_info "Total:     $TOTAL"
log_info "Completed: $COMPLETED"
log_info "Failed:    $FAILED"
log_info "Skipped:   $SKIPPED"
log_info "Duration:  ${ELAPSED}s"
log_info "State:     $STATE_FILE"
log_info "Reports:   $REPORT_DIR"
log_info "============================================================"

if [[ "$FAILED" -gt 0 ]]; then
  log_error "Failed instances:"
  jq -r '.instances | to_entries[] | select(.value.status == "FAILED") | "  \(.key): \(.value.detail // "unknown")"' "$STATE_FILE"
fi
